---
- name: tmpserver
  hosts: all
  sudo: true
  user: vagrant
  vars:
    hostname: tmpserver.vagrant
    username: fusic
    docroot: /var/www/html/
  roles:
    - common
    - apache
    - php
    - xdebug
    - mysql
